name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npx eslint .

      - name: Unit tests
        run: npm test -- --coverage

      - name: Start dev server
        run: npm run dev &
        env:
          CI: true
        # Give server time to boot
      - name: Wait for server
        run: npx wait-on http://localhost:8000

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: npm run dev
          wait-on: 'http://localhost:8000'

      - name: Stop server
        run: kill $(lsof -t -i:8000) || true
